# Generated by Django 2.1.7 on 2023-05-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_task_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-due_date']},
        ),
        migrations.AddField(
            model_name='task',
            name='is_skipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='remind_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
