FROM python:3.10.11-slim-buster

ENV PYTHONUNBUFFERED=1

WORKDIR /django1

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt


COPY . .

CMD python manage.py runserver 0.0.0.0:8000