version: '3.10.11'
services:
  app:
    build: .
    volumes:
      - .:/sdp
    ports: 
      - "8000:8000"
    image: sdp:spd
    container_name: sdp_container
    command: python manage.py runserver 0.0.0.0:8000
   